### ISSUE TITLE
Where do I find/place the cordova.js file?

### ISSUE THREAD

**Issue by alshdavid** [phonegap/phonegap-start#207]
It's not included in this repo and I need access to the camera.
I haven't been able to find any documentation on how to access the camera and I am using the Adobe PhoneGap web builder

**Comment by englishextra** [comment]
You dont have to add it in your root or anywhere else, but you should keep the link to it. Because it will appear in the root of your app when it will be compiled into apk for instance with build.phonegap.com or whatever tool you use. So dont bother but keep the script link and dont place cordova.js by yourself

**Comment by Radivarig** [comment]
Add this to the `<body>` of your `index.html`
```html
<script type="text/javascript" src="cordova.js"></script>
```

**Comment by macdonst** [comment]
Hi, we don't really track the issues on this repo and we ask that folks having problems with PhoneGap please use our forum:

https://forums.adobe.com/community/phonegap
